--------------------------------------------------------
--  File created - Friday-March-31-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_TEACHER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_TEACHER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"DESIGNATION" VARCHAR2(20 BYTE), 
	"BIRTHDATE" VARCHAR2(10 BYTE), 
	"GENDER" VARCHAR2(11 BYTE), 
	"BLOODGROUP" VARCHAR2(5 BYTE), 
	"RELIGION" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"MOBILE" VARCHAR2(15 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"JOINDATE" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBL_TEACHER
SET DEFINE OFF;
Insert into SYSTEM.TBL_TEACHER (ID,NAME,DESIGNATION,BIRTHDATE,GENDER,BLOODGROUP,RELIGION,EMAIL,MOBILE,ADDRESS,JOINDATE,PASSWORD) values (1,'Md. Rafayet Alam','Professor','31-05-1994','Female','AB+','Islam','rafayet.monon@gmail.com','+8801829647695','Boyra, Khulna','01-01-2016','12345');
Insert into SYSTEM.TBL_TEACHER (ID,NAME,DESIGNATION,BIRTHDATE,GENDER,BLOODGROUP,RELIGION,EMAIL,MOBILE,ADDRESS,JOINDATE,PASSWORD) values (3,'Md. Golam Rased','Professor','08-08-1995','Male','O+','Islam','golam.raashed@gmail.com','+8801760003250','Muladi, Barisal','01-01-2015','12345');
Insert into SYSTEM.TBL_TEACHER (ID,NAME,DESIGNATION,BIRTHDATE,GENDER,BLOODGROUP,RELIGION,EMAIL,MOBILE,ADDRESS,JOINDATE,PASSWORD) values (5,'Rashed','Professor','08-08-1995','Male','O+','Islam','golam.raashed@gmail.com','01760003250','Barisal','01-01-2016','12345');
--------------------------------------------------------
--  DDL for Index SYS_C007054
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007054" ON "SYSTEM"."TBL_TEACHER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_TEACHER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_TEACHER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TBL_TEACHER" MODIFY ("ID" NOT NULL ENABLE);
