--------------------------------------------------------
--  File created - Friday-March-31-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_ADMIN" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBL_ADMIN
SET DEFINE OFF;
Insert into SYSTEM.TBL_ADMIN (ID,NAME,EMAIL,PASSWORD) values (1,'Md. Golam Rased','golam.raashed@gmail.com','12345');
Insert into SYSTEM.TBL_ADMIN (ID,NAME,EMAIL,PASSWORD) values (3,'Md. Golam Rased','rashed','12345');
--------------------------------------------------------
--  DDL for Index SYS_C007012
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007012" ON "SYSTEM"."TBL_ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_ADMIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TBL_ADMIN" MODIFY ("ID" NOT NULL ENABLE);
